In [32]:
df_learn = pd.read_csv('../data/train.csv')
df_learn.head()

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0

In [33]:
df = pd.read_csv("../data/features/features_part_one.csv",index_col=0)
print(df.shape)
df.head()

(404288, 37)

,CC,CD,DT,EX,FW,IN,JJ,JJR,JJS,LS,...,VBD,VBG,VBN,VBP,VBZ,WDT,WP,WP$,WRB,length
0,NaN,NaN,1.0,NaN,NaN,1.5,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.166667
1,NaN,NaN,0.5,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,0.615385
2,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.400000
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.687500
4,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.857143

In [34]:
y = df_learn['is_duplicate']

In [35]:
df.replace([np.inf, -np.inf], np.nan,inplace=True)
df.fillna(0.0,inplace=True)
df.head()

,CC,CD,DT,EX,FW,IN,JJ,JJR,JJS,LS,...,VBD,VBG,VBN,VBP,VBZ,WDT,WP,WP$,WRB,length
0,0.0,0.0,1.0,0.0,0.0,1.5,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.166667
1,0.0,0.0,0.5,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.615385
2,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.400000
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.687500
4,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.857143

In [36]:
df.describe()

,CC,CD,DT,EX,FW,IN,JJ,JJR,JJS,LS,...,VBD,VBG,VBN,VBP,VBZ,WDT,WP,WP$,WRB,length
count,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,...,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000,404288.000000
mean,0.108492,0.082281,0.514885,0.004825,0.000502,0.642276,0.393511,0.007753,0.064297,0.000002,...,0.042173,0.068119,0.053261,0.245794,0.288016,0.018351,0.292856,0.000047,0.278304,1.099075
std,0.344629,0.321532,0.698966,0.069669,0.022987,0.767546,0.647369,0.090826,0.248543,0.001573,...,0.228601,0.272316,0.242372,0.500626,0.502773,0.135902,0.468204,0.006855,0.470740,0.572705
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.785714
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.500000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
75%,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.250000
max,6.000000,16.000000,11.000000,3.000000,3.000000,13.000000,11.000000,4.000000,4.000000,1.000000,...,7.000000,5.000000,5.000000,9.000000,8.000000,3.000000,4.000000,1.000000,4.000000,29.000000

In [53]:
from sklearn.preprocessing import StandardScaler
norm = StandardScaler()

d = set()
d.add('length')
f_tags = list(set(df.columns) - d)

df_norm = pd.DataFrame(norm.fit_transform(df[f_tags]),columns=f_tags)
df_norm['length'] = df.length
df_norm.describe()

,VBP,NN,MD,PDT,RB,UH,VBZ,EX,DT,JJS,...,FW,VBG,VBN,JJ,NNP,LS,WDT,RBS,WRB,length
count,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,...,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,4.042880e+05,404286.000000
mean,2.499325e-15,2.936396e-15,7.639882e-15,-5.111779e-15,-1.583100e-14,3.434396e-15,5.920084e-18,1.640363e-15,9.400680e-17,1.867844e-15,...,1.473002e-15,-3.414673e-15,-4.164740e-16,2.462100e-15,-2.772855e-15,6.968203e-15,3.900150e-15,2.453709e-15,2.522717e-16,1.099077
std,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,...,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,1.000001e+00,0.572706
min,-4.909732e-01,-9.421277e-01,-3.815914e-01,-2.079356e-02,-2.739364e-01,-5.884724e-03,-5.728558e-01,-6.924899e-02,-7.366393e-01,-2.586978e-01,...,-2.182521e-02,-2.501459e-01,-2.197486e-01,-6.078636e-01,-5.750366e-01,-1.572733e-03,-1.350343e-01,-1.034119e-01,-5.912073e-01,0.000000
25%,-4.909732e-01,-9.421277e-01,-3.815914e-01,-2.079356e-02,-2.739364e-01,-5.884724e-03,-5.728558e-01,-6.924899e-02,-7.366393e-01,-2.586978e-01,...,-2.182521e-02,-2.501459e-01,-2.197486e-01,-6.078636e-01,-5.750366e-01,-1.572733e-03,-1.350343e-01,-1.034119e-01,-5.912073e-01,0.785714
50%,-4.909732e-01,1.624623e-01,-3.815914e-01,-2.079356e-02,-2.739364e-01,-5.884724e-03,-5.728558e-01,-6.924899e-02,-7.366393e-01,-2.586978e-01,...,-2.182521e-02,-2.501459e-01,-2.197486e-01,-6.078636e-01,-5.750366e-01,-1.572733e-03,-1.350343e-01,-1.034119e-01,-5.912073e-01,1.000000
75%,-4.909732e-01,1.624623e-01,-3.815914e-01,-2.079356e-02,-2.739364e-01,-5.884724e-03,1.416116e+00,-6.924899e-02,6.940482e-01,-2.586978e-01,...,-2.182521e-02,-2.501459e-01,-2.197486e-01,9.368536e-01,7.519147e-01,-1.572733e-03,-1.350343e-01,-1.034119e-01,1.533112e+00,1.250000
max,1.748655e+01,1.894049e+01,2.465390e+01,9.037260e+01,1.915711e+01,1.699315e+02,1.533892e+01,4.299130e+01,1.500092e+01,1.583513e+01,...,1.304844e+02,1.811086e+01,2.040972e+01,1.638403e+01,2.994484e+01,6.358357e+02,2.193974e+01,1.924104e+01,7.906068e+00,29.000000